name: dibasys_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter_screenutil: ^5.9.3
  provider: ^6.1.5
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
  fonts:
    - family: InterTight
      fonts:
        - asset: assets/fonts/InterTight-Thin.ttf
          weight: 100
        - asset: assets/fonts/InterTight-ThinItalic.ttf
          weight: 100
          style: italic

        - asset: assets/fonts/InterTight-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/InterTight-ExtraLightItalic.ttf
          weight: 200
          style: italic

        - asset: assets/fonts/InterTight-Light.ttf
          weight: 300
        - asset: assets/fonts/InterTight-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/InterTight-Regular.ttf
          weight: 400

        - asset: assets/fonts/InterTight-Medium.ttf
          weight: 500
        - asset: assets/fonts/InterTight-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/InterTight-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterTight-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: assets/fonts/InterTight-Bold.ttf
          weight: 700
        - asset: assets/fonts/InterTight-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/InterTight-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/InterTight-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: assets/fonts/InterTight-Black.ttf
          weight: 900
        - asset: assets/fonts/InterTight-BlackItalic.ttf
          weight: 900
          style: italic